// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: record.proto

package microtraffic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State of a recording for a given session id.
type RecordingState int32

const (
	RecordingState_RECORDING_STATE_UNSPECIFIED RecordingState = 0
	// No recording is currently running for this session id.
	RecordingState_RECORDING_STATE_NOT_RUNNING RecordingState = 1
	// A recording is currently running.
	RecordingState_RECORDING_STATE_RUNNING RecordingState = 2
)

// Enum value maps for RecordingState.
var (
	RecordingState_name = map[int32]string{
		0: "RECORDING_STATE_UNSPECIFIED",
		1: "RECORDING_STATE_NOT_RUNNING",
		2: "RECORDING_STATE_RUNNING",
	}
	RecordingState_value = map[string]int32{
		"RECORDING_STATE_UNSPECIFIED": 0,
		"RECORDING_STATE_NOT_RUNNING": 1,
		"RECORDING_STATE_RUNNING":     2,
	}
)

func (x RecordingState) Enum() *RecordingState {
	p := new(RecordingState)
	*p = x
	return p
}

func (x RecordingState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordingState) Descriptor() protoreflect.EnumDescriptor {
	return file_record_proto_enumTypes[0].Descriptor()
}

func (RecordingState) Type() protoreflect.EnumType {
	return &file_record_proto_enumTypes[0]
}

func (x RecordingState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordingState.Descriptor instead.
func (RecordingState) EnumDescriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{0}
}

// Request to run a loaded session forward and stream its recorded trajectory.
// The session must already exist and have at least its grid pushed (via the
// Push* RPCs).
type RunAndRecordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target session (must already exist and be initialized).
	SessionId *UUIDv4 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Number of ticks to advance from the session's current tick.
	// 0 = run until the configured maximum / no further active vehicles.
	HorizonTicks uint64 `protobuf:"varint,2,opt,name=horizon_ticks,json=horizonTicks,proto3" json:"horizon_ticks,omitempty"`
	// K: number of ticks packed into one RecordBatch. 0 -> server default (~300).
	// This is a MEMORY <-> COMPRESSION knob, NOT a throughput knob: larger K
	// buffers more rows before flush (~ K * vehicles * 21 bytes) and compresses
	// slightly better, while packing cost stays ~flat in K.
	BatchTicks uint32 `protobuf:"varint,3,opt,name=batch_ticks,json=batchTicks,proto3" json:"batch_ticks,omitempty"`
	// Optional write-time reduction. LEAVE EMPTY FOR VALIDATION RUNS - any
	// sampling/subsetting silently degrades a micro recording toward a sparse
	// aggregate (the macro one-shot model we explicitly do not want here).
	Filter        *RecordFilter `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAndRecordRequest) Reset() {
	*x = RunAndRecordRequest{}
	mi := &file_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAndRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAndRecordRequest) ProtoMessage() {}

func (x *RunAndRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAndRecordRequest.ProtoReflect.Descriptor instead.
func (*RunAndRecordRequest) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{0}
}

func (x *RunAndRecordRequest) GetSessionId() *UUIDv4 {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *RunAndRecordRequest) GetHorizonTicks() uint64 {
	if x != nil {
		return x.HorizonTicks
	}
	return 0
}

func (x *RunAndRecordRequest) GetBatchTicks() uint32 {
	if x != nil {
		return x.BatchTicks
	}
	return 0
}

func (x *RunAndRecordRequest) GetFilter() *RecordFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Optional, lossy, write-time data reduction. Empty = full fidelity (every tick,
// all vehicles).
type RecordFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Record every Nth tick. 0 or 1 = every tick.
	SamplePeriod uint32 `protobuf:"varint,1,opt,name=sample_period,json=samplePeriod,proto3" json:"sample_period,omitempty"`
	// Restrict recorded vehicles to those on these meso links. Empty = all.
	MesoLinkIds   []int64 `protobuf:"varint,2,rep,packed,name=meso_link_ids,json=mesoLinkIds,proto3" json:"meso_link_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordFilter) Reset() {
	*x = RecordFilter{}
	mi := &file_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFilter) ProtoMessage() {}

func (x *RecordFilter) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFilter.ProtoReflect.Descriptor instead.
func (*RecordFilter) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{1}
}

func (x *RecordFilter) GetSamplePeriod() uint32 {
	if x != nil {
		return x.SamplePeriod
	}
	return 0
}

func (x *RecordFilter) GetMesoLinkIds() []int64 {
	if x != nil {
		return x.MesoLinkIds
	}
	return nil
}

// Streamed response. Ordering is strict:
//
//	1x RunMetadata (first) -> N x RecordBatch (ascending tick order) -> 1x RunSummary (last)
type RunAndRecordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RunAndRecordResponse_Metadata
	//	*RunAndRecordResponse_Batch
	//	*RunAndRecordResponse_Summary
	Payload       isRunAndRecordResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAndRecordResponse) Reset() {
	*x = RunAndRecordResponse{}
	mi := &file_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAndRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAndRecordResponse) ProtoMessage() {}

func (x *RunAndRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAndRecordResponse.ProtoReflect.Descriptor instead.
func (*RunAndRecordResponse) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{2}
}

func (x *RunAndRecordResponse) GetPayload() isRunAndRecordResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RunAndRecordResponse) GetMetadata() *RunMetadata {
	if x != nil {
		if x, ok := x.Payload.(*RunAndRecordResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *RunAndRecordResponse) GetBatch() *RecordBatch {
	if x != nil {
		if x, ok := x.Payload.(*RunAndRecordResponse_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

func (x *RunAndRecordResponse) GetSummary() *RunSummary {
	if x != nil {
		if x, ok := x.Payload.(*RunAndRecordResponse_Summary); ok {
			return x.Summary
		}
	}
	return nil
}

type isRunAndRecordResponse_Payload interface {
	isRunAndRecordResponse_Payload()
}

type RunAndRecordResponse_Metadata struct {
	// Sent exactly once, before any batch.
	Metadata *RunMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type RunAndRecordResponse_Batch struct {
	// Zero or more, in ascending tick order.
	Batch *RecordBatch `protobuf:"bytes,2,opt,name=batch,proto3,oneof"`
}

type RunAndRecordResponse_Summary struct {
	// Sent exactly once, after the last batch.
	Summary *RunSummary `protobuf:"bytes,3,opt,name=summary,proto3,oneof"`
}

func (*RunAndRecordResponse_Metadata) isRunAndRecordResponse_Payload() {}

func (*RunAndRecordResponse_Batch) isRunAndRecordResponse_Payload() {}

func (*RunAndRecordResponse_Summary) isRunAndRecordResponse_Payload() {}

// Everything needed to interpret AND reproduce the recording. Persist this
// alongside the Parquet file.
//
// Reproducibility requires pinning BOTH seeds: the core has two independent RNG
// streams (vehicle spawning vs. per-tick NaSch slowdown / conflict tie-break /
// reroute), and the per-tick stream is entropy-seeded in production unless
// MTSC_SEED is set. The recording itself is therefore the canonical replay
// source; re-running from seeds is best-effort only, and is impossible at all
// for runs altered by live what-if edits.
type RunMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Layout version of the RecordBatch.columns blob (see RECORD BLOB LAYOUT).
	FormatVersion uint32 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	// dt: simulated seconds per tick. Maps tick index -> wall time on the replay
	// timeline.
	TickSeconds float64 `protobuf:"fixed64,2,opt,name=tick_seconds,json=tickSeconds,proto3" json:"tick_seconds,omitempty"`
	// Vehicle-spawning RNG seed (core SPAWN_SEED).
	SpawnSeed uint64 `protobuf:"varint,3,opt,name=spawn_seed,json=spawnSeed,proto3" json:"spawn_seed,omitempty"`
	// Per-tick stochastic RNG seed (core MTSC_SEED). MUST be pinned for any
	// re-run to match.
	StochasticSeed uint64 `protobuf:"varint,4,opt,name=stochastic_seed,json=stochasticSeed,proto3" json:"stochastic_seed,omitempty"`
	// micro_traffic_sim_core version and/or git commit that produced this run.
	CoreVersion string `protobuf:"bytes,5,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	// rand crate version: StdRng's byte stream is NOT stable across rand major
	// versions, so the same seed on a different rand can diverge.
	RandVersion string `protobuf:"bytes,6,opt,name=rand_version,json=randVersion,proto3" json:"rand_version,omitempty"`
	// Hash of the inputs (grid + trips + TLS + routing options).
	ConfigHash string `protobuf:"bytes,7,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	// Self-describing per-vehicle-row column layout of the blob, for reader-side
	// validation / forward-compat.
	Schema *ColumnSchema `protobuf:"bytes,8,opt,name=schema,proto3" json:"schema,omitempty"`
	// Self-describing layout of the per-tick traffic-light signal section that
	// follows the vehicle columns in the blob (see RECORD BLOB LAYOUT). Column
	// types carry the element shape, e.g. "u8[tick_count*tl_group_count]".
	TlSchema      *ColumnSchema `protobuf:"bytes,9,opt,name=tl_schema,json=tlSchema,proto3" json:"tl_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunMetadata) Reset() {
	*x = RunMetadata{}
	mi := &file_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunMetadata) ProtoMessage() {}

func (x *RunMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunMetadata.ProtoReflect.Descriptor instead.
func (*RunMetadata) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{3}
}

func (x *RunMetadata) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *RunMetadata) GetTickSeconds() float64 {
	if x != nil {
		return x.TickSeconds
	}
	return 0
}

func (x *RunMetadata) GetSpawnSeed() uint64 {
	if x != nil {
		return x.SpawnSeed
	}
	return 0
}

func (x *RunMetadata) GetStochasticSeed() uint64 {
	if x != nil {
		return x.StochasticSeed
	}
	return 0
}

func (x *RunMetadata) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *RunMetadata) GetRandVersion() string {
	if x != nil {
		return x.RandVersion
	}
	return ""
}

func (x *RunMetadata) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *RunMetadata) GetSchema() *ColumnSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *RunMetadata) GetTlSchema() *ColumnSchema {
	if x != nil {
		return x.TlSchema
	}
	return nil
}

// Declares the column order and element types of the columnar blob.
type ColumnSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*ColumnDef           `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnSchema) Reset() {
	*x = ColumnSchema{}
	mi := &file_record_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnSchema) ProtoMessage() {}

func (x *ColumnSchema) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnSchema.ProtoReflect.Descriptor instead.
func (*ColumnSchema) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{4}
}

func (x *ColumnSchema) GetColumns() []*ColumnDef {
	if x != nil {
		return x.Columns
	}
	return nil
}

type ColumnDef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column name, e.g. "cell".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Element type, e.g. "u32", "u8", "u16", "i16", or "list<u32>".
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnDef) Reset() {
	*x = ColumnDef{}
	mi := &file_record_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnDef) ProtoMessage() {}

func (x *ColumnDef) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnDef.ProtoReflect.Descriptor instead.
func (*ColumnDef) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{5}
}

func (x *ColumnDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnDef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// One columnar batch covering ticks [tick_start, tick_start + tick_count).
//
// `columns` is an OPAQUE, version-tagged, little-endian binary blob - NOT
// protobuf - packed column-major. It is kept opaque on purpose: wrapping each
// scalar as a protobuf field would re-introduce per-field tag/framing overhead
// for millions of rows. The proto envelope carries only a few routing/progress
// scalars so the consumer can track progress without decoding the blob; the
// AUTHORITATIVE copies of version/tick_start/total_rows live inside the blob,
// which is fully self-describing and can be persisted as-is.
//
// -------------------------- RECORD BLOB LAYOUT --------------------------------
// All integers little-endian. R = total_rows = sum over the K ticks of that
// tick's active-vehicle count.
//
// Header:
//
//	u8   version                 // == RunMetadata.format_version; bump on ANY change
//	u32  tick_start              // first tick (authoritative)
//	u32  tick_count              // K
//	u32  total_rows              // R
//
// Per-tick index (slice columns by tick without scanning):
//
//	u32  rows_per_tick[tick_count]   // vehicles at each tick; prefix-sum = row offsets
//
// Fixed-width columns, column-major, each of length R:
//
//	u32  vehicle_id[R]
//	u32  cell[R]                 // head cell id; geometry is resolved client-side from
//	                             //   the static grid - NO coordinates are ever on the wire
//	u8   agent_type[R]           // 0=Undefined 1=Car 2=Bus 3=Taxi 4=Pedestrian 5=Truck 6=LargeBus
//	u16  angle_cdeg[R]           // bearing in centidegrees, normalized to [0,360); round(degrees*100)
//	i16  speed[R]                // cells per tick
//	u32  trip_id[R]
//
// Variable-length columns. Each is an offsets array (cumulative end-offset per
// row; row i's slice = vals[off[i-1] .. off[i]], off[-1] := 0) plus a flat values
// array:
//
//	u32  ic_off[R]               // intermediate_cells: cells crossed THIS tick when speed>1.
//	u32  ic_vals[ic_off[R-1]]    //   REQUIRED for cell-level analytics: a vehicle's passage
//	                             //   this tick is attributed to head `cell` PLUS every cell in
//	                             //   ic_vals (otherwise fast vehicles undercount intermediate cells).
//	u32  tail_off[R]             // tail_cells of multi-cell vehicles (bus / truck / large_bus).
//	u32  tail_vals[tail_off[R-1]]    // flattened tail cell ids
//
// Traffic-light signals. The TL config is fixed for a run, so the group set
// is constant; the per-tick signal of every group is recorded in a fixed key order:
//
//	u32  tl_group_count          // G = number of (tl_id, group_id) pairs
//	{ u32 tl_id; u32 group_id }[G]   // the keys, sorted ascending
//	u8   signal[tick_count * G]  // tick-major: tick k's G codes at [k*G .. k*G+G)
//	                             //   0=undefined 1=r 2=y 3=g 4=G 5=s 6=u 7=o 8=O
//
// Notes:
//   - Column-major + cell-id (no geometry) is what makes the blob compress several-fold
//     (measured, gzip; Parquet dictionary+RLE+zstd is comparable). Compression is
//     the WRITER's (Go) responsibility - the blob is streamed RAW/uncompressed.
//   - angle/speed/agent_type are quantized; bump `version` if a wider range or
//     sub-degree precision is ever required.
//   - Row order within a tick is the session's vehicle-iteration order and is NOT
//     guaranteed stable across ticks (vehicles spawn/despawn). Readers MUST key
//     vehicles by vehicle_id, never by row index.
//   - VehicleState.travel_time is intentionally NOT stored: it is a pure
//     per-vehicle age counter (+1 every tick from spawn, including while stopped),
//     which is high-cardinality (compresses poorly) AND fully derivable. Readers
//     reconstruct it as (tick - first_recorded_tick) for each vehicle_id - exact
//     for recordings started at session begin.
//
// ------------------------------------------------------------------------------
type RecordBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First tick in this batch (mirror of the blob header, for cheap progress).
	TickStart uint64 `protobuf:"varint,1,opt,name=tick_start,json=tickStart,proto3" json:"tick_start,omitempty"`
	// Number of ticks in this batch (K, except possibly the final flushed batch).
	TickCount uint32 `protobuf:"varint,2,opt,name=tick_count,json=tickCount,proto3" json:"tick_count,omitempty"`
	// Sum of vehicle rows across the batch (mirror, for buffer sizing).
	TotalRows uint32 `protobuf:"varint,3,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	// The columnar blob (see RECORD BLOB LAYOUT above).
	Columns       []byte `protobuf:"bytes,4,opt,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordBatch) Reset() {
	*x = RecordBatch{}
	mi := &file_record_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordBatch) ProtoMessage() {}

func (x *RecordBatch) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordBatch.ProtoReflect.Descriptor instead.
func (*RecordBatch) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{6}
}

func (x *RecordBatch) GetTickStart() uint64 {
	if x != nil {
		return x.TickStart
	}
	return 0
}

func (x *RecordBatch) GetTickCount() uint32 {
	if x != nil {
		return x.TickCount
	}
	return 0
}

func (x *RecordBatch) GetTotalRows() uint32 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *RecordBatch) GetColumns() []byte {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Final tallies, sent once after the last batch.
type RunSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ticks actually advanced.
	TotalTicks uint64 `protobuf:"varint,1,opt,name=total_ticks,json=totalTicks,proto3" json:"total_ticks,omitempty"`
	// Total vehicle-ticks (rows) recorded.
	TotalRows uint64 `protobuf:"varint,2,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	// Total uncompressed bytes of `columns` streamed.
	TotalBytes uint64 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// Cumulative vehicles that reached their destination.
	VehiclesCompleted int32 `protobuf:"varint,4,opt,name=vehicles_completed,json=vehiclesCompleted,proto3" json:"vehicles_completed,omitempty"`
	// Cumulative vehicles lost (despawned in a death zone without arriving).
	VehiclesLost  int32 `protobuf:"varint,5,opt,name=vehicles_lost,json=vehiclesLost,proto3" json:"vehicles_lost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSummary) Reset() {
	*x = RunSummary{}
	mi := &file_record_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSummary) ProtoMessage() {}

func (x *RunSummary) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSummary.ProtoReflect.Descriptor instead.
func (*RunSummary) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{7}
}

func (x *RunSummary) GetTotalTicks() uint64 {
	if x != nil {
		return x.TotalTicks
	}
	return 0
}

func (x *RunSummary) GetTotalRows() uint64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *RunSummary) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *RunSummary) GetVehiclesCompleted() int32 {
	if x != nil {
		return x.VehiclesCompleted
	}
	return 0
}

func (x *RunSummary) GetVehiclesLost() int32 {
	if x != nil {
		return x.VehiclesLost
	}
	return 0
}

type RecordingStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session whose recording to query.
	SessionId     *UUIDv4 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordingStatusRequest) Reset() {
	*x = RecordingStatusRequest{}
	mi := &file_record_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingStatusRequest) ProtoMessage() {}

func (x *RecordingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingStatusRequest.ProtoReflect.Descriptor instead.
func (*RecordingStatusRequest) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{8}
}

func (x *RecordingStatusRequest) GetSessionId() *UUIDv4 {
	if x != nil {
		return x.SessionId
	}
	return nil
}

type RecordingStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether a recording is running for this session id.
	State RecordingState `protobuf:"varint,1,opt,name=state,proto3,enum=micro_traffic_sim.RecordingState" json:"state,omitempty"`
	// Last tick recorded so far (meaningful only when RUNNING).
	CurrentTick uint64 `protobuf:"varint,2,opt,name=current_tick,json=currentTick,proto3" json:"current_tick,omitempty"`
	// Vehicle-ticks recorded so far (meaningful only when RUNNING).
	Rows uint64 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	// Whether a stop has already been requested for this recording.
	CancelRequested bool `protobuf:"varint,4,opt,name=cancel_requested,json=cancelRequested,proto3" json:"cancel_requested,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecordingStatusResponse) Reset() {
	*x = RecordingStatusResponse{}
	mi := &file_record_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingStatusResponse) ProtoMessage() {}

func (x *RecordingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingStatusResponse.ProtoReflect.Descriptor instead.
func (*RecordingStatusResponse) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{9}
}

func (x *RecordingStatusResponse) GetState() RecordingState {
	if x != nil {
		return x.State
	}
	return RecordingState_RECORDING_STATE_UNSPECIFIED
}

func (x *RecordingStatusResponse) GetCurrentTick() uint64 {
	if x != nil {
		return x.CurrentTick
	}
	return 0
}

func (x *RecordingStatusResponse) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *RecordingStatusResponse) GetCancelRequested() bool {
	if x != nil {
		return x.CancelRequested
	}
	return false
}

type StopRecordingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session whose recording to stop.
	SessionId     *UUIDv4 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRecordingRequest) Reset() {
	*x = StopRecordingRequest{}
	mi := &file_record_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRecordingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordingRequest) ProtoMessage() {}

func (x *StopRecordingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordingRequest.ProtoReflect.Descriptor instead.
func (*StopRecordingRequest) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{10}
}

func (x *StopRecordingRequest) GetSessionId() *UUIDv4 {
	if x != nil {
		return x.SessionId
	}
	return nil
}

type StopRecordingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if a running recording was found and a stop was requested; false if no
	// recording is running for this session id. The stop is cooperative: the run
	// finalizes its current batch, sends RunSummary, and ends.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRecordingResponse) Reset() {
	*x = StopRecordingResponse{}
	mi := &file_record_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRecordingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordingResponse) ProtoMessage() {}

func (x *StopRecordingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordingResponse.ProtoReflect.Descriptor instead.
func (*StopRecordingResponse) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{11}
}

func (x *StopRecordingResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_record_proto protoreflect.FileDescriptor

const file_record_proto_rawDesc = "" +
	"\n" +
	"\frecord.proto\x12\x11micro_traffic_sim\x1a\n" +
	"uuid.proto\"\xce\x01\n" +
	"\x13RunAndRecordRequest\x128\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2\x19.micro_traffic_sim.UUIDv4R\tsessionId\x12#\n" +
	"\rhorizon_ticks\x18\x02 \x01(\x04R\fhorizonTicks\x12\x1f\n" +
	"\vbatch_ticks\x18\x03 \x01(\rR\n" +
	"batchTicks\x127\n" +
	"\x06filter\x18\x04 \x01(\v2\x1f.micro_traffic_sim.RecordFilterR\x06filter\"W\n" +
	"\fRecordFilter\x12#\n" +
	"\rsample_period\x18\x01 \x01(\rR\fsamplePeriod\x12\"\n" +
	"\rmeso_link_ids\x18\x02 \x03(\x03R\vmesoLinkIds\"\xd2\x01\n" +
	"\x14RunAndRecordResponse\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.micro_traffic_sim.RunMetadataH\x00R\bmetadata\x126\n" +
	"\x05batch\x18\x02 \x01(\v2\x1e.micro_traffic_sim.RecordBatchH\x00R\x05batch\x129\n" +
	"\asummary\x18\x03 \x01(\v2\x1d.micro_traffic_sim.RunSummaryH\x00R\asummaryB\t\n" +
	"\apayload\"\xfd\x02\n" +
	"\vRunMetadata\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12!\n" +
	"\ftick_seconds\x18\x02 \x01(\x01R\vtickSeconds\x12\x1d\n" +
	"\n" +
	"spawn_seed\x18\x03 \x01(\x04R\tspawnSeed\x12'\n" +
	"\x0fstochastic_seed\x18\x04 \x01(\x04R\x0estochasticSeed\x12!\n" +
	"\fcore_version\x18\x05 \x01(\tR\vcoreVersion\x12!\n" +
	"\frand_version\x18\x06 \x01(\tR\vrandVersion\x12\x1f\n" +
	"\vconfig_hash\x18\a \x01(\tR\n" +
	"configHash\x127\n" +
	"\x06schema\x18\b \x01(\v2\x1f.micro_traffic_sim.ColumnSchemaR\x06schema\x12<\n" +
	"\ttl_schema\x18\t \x01(\v2\x1f.micro_traffic_sim.ColumnSchemaR\btlSchema\"F\n" +
	"\fColumnSchema\x126\n" +
	"\acolumns\x18\x01 \x03(\v2\x1c.micro_traffic_sim.ColumnDefR\acolumns\"3\n" +
	"\tColumnDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x84\x01\n" +
	"\vRecordBatch\x12\x1d\n" +
	"\n" +
	"tick_start\x18\x01 \x01(\x04R\ttickStart\x12\x1d\n" +
	"\n" +
	"tick_count\x18\x02 \x01(\rR\ttickCount\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x03 \x01(\rR\ttotalRows\x12\x18\n" +
	"\acolumns\x18\x04 \x01(\fR\acolumns\"\xc1\x01\n" +
	"\n" +
	"RunSummary\x12\x1f\n" +
	"\vtotal_ticks\x18\x01 \x01(\x04R\n" +
	"totalTicks\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x02 \x01(\x04R\ttotalRows\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\x12-\n" +
	"\x12vehicles_completed\x18\x04 \x01(\x05R\x11vehiclesCompleted\x12#\n" +
	"\rvehicles_lost\x18\x05 \x01(\x05R\fvehiclesLost\"R\n" +
	"\x16RecordingStatusRequest\x128\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2\x19.micro_traffic_sim.UUIDv4R\tsessionId\"\xb4\x01\n" +
	"\x17RecordingStatusResponse\x127\n" +
	"\x05state\x18\x01 \x01(\x0e2!.micro_traffic_sim.RecordingStateR\x05state\x12!\n" +
	"\fcurrent_tick\x18\x02 \x01(\x04R\vcurrentTick\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x04R\x04rows\x12)\n" +
	"\x10cancel_requested\x18\x04 \x01(\bR\x0fcancelRequested\"P\n" +
	"\x14StopRecordingRequest\x128\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2\x19.micro_traffic_sim.UUIDv4R\tsessionId\"3\n" +
	"\x15StopRecordingResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted*o\n" +
	"\x0eRecordingState\x12\x1f\n" +
	"\x1bRECORDING_STATE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bRECORDING_STATE_NOT_RUNNING\x10\x01\x12\x1b\n" +
	"\x17RECORDING_STATE_RUNNING\x10\x02B@Z>github.com/LdDl/micro_traffic_sim_grpc/clients/go;microtrafficb\x06proto3"

var (
	file_record_proto_rawDescOnce sync.Once
	file_record_proto_rawDescData []byte
)

func file_record_proto_rawDescGZIP() []byte {
	file_record_proto_rawDescOnce.Do(func() {
		file_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_record_proto_rawDesc), len(file_record_proto_rawDesc)))
	})
	return file_record_proto_rawDescData
}

var file_record_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_record_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_record_proto_goTypes = []any{
	(RecordingState)(0),             // 0: micro_traffic_sim.RecordingState
	(*RunAndRecordRequest)(nil),     // 1: micro_traffic_sim.RunAndRecordRequest
	(*RecordFilter)(nil),            // 2: micro_traffic_sim.RecordFilter
	(*RunAndRecordResponse)(nil),    // 3: micro_traffic_sim.RunAndRecordResponse
	(*RunMetadata)(nil),             // 4: micro_traffic_sim.RunMetadata
	(*ColumnSchema)(nil),            // 5: micro_traffic_sim.ColumnSchema
	(*ColumnDef)(nil),               // 6: micro_traffic_sim.ColumnDef
	(*RecordBatch)(nil),             // 7: micro_traffic_sim.RecordBatch
	(*RunSummary)(nil),              // 8: micro_traffic_sim.RunSummary
	(*RecordingStatusRequest)(nil),  // 9: micro_traffic_sim.RecordingStatusRequest
	(*RecordingStatusResponse)(nil), // 10: micro_traffic_sim.RecordingStatusResponse
	(*StopRecordingRequest)(nil),    // 11: micro_traffic_sim.StopRecordingRequest
	(*StopRecordingResponse)(nil),   // 12: micro_traffic_sim.StopRecordingResponse
	(*UUIDv4)(nil),                  // 13: micro_traffic_sim.UUIDv4
}
var file_record_proto_depIdxs = []int32{
	13, // 0: micro_traffic_sim.RunAndRecordRequest.session_id:type_name -> micro_traffic_sim.UUIDv4
	2,  // 1: micro_traffic_sim.RunAndRecordRequest.filter:type_name -> micro_traffic_sim.RecordFilter
	4,  // 2: micro_traffic_sim.RunAndRecordResponse.metadata:type_name -> micro_traffic_sim.RunMetadata
	7,  // 3: micro_traffic_sim.RunAndRecordResponse.batch:type_name -> micro_traffic_sim.RecordBatch
	8,  // 4: micro_traffic_sim.RunAndRecordResponse.summary:type_name -> micro_traffic_sim.RunSummary
	5,  // 5: micro_traffic_sim.RunMetadata.schema:type_name -> micro_traffic_sim.ColumnSchema
	5,  // 6: micro_traffic_sim.RunMetadata.tl_schema:type_name -> micro_traffic_sim.ColumnSchema
	6,  // 7: micro_traffic_sim.ColumnSchema.columns:type_name -> micro_traffic_sim.ColumnDef
	13, // 8: micro_traffic_sim.RecordingStatusRequest.session_id:type_name -> micro_traffic_sim.UUIDv4
	0,  // 9: micro_traffic_sim.RecordingStatusResponse.state:type_name -> micro_traffic_sim.RecordingState
	13, // 10: micro_traffic_sim.StopRecordingRequest.session_id:type_name -> micro_traffic_sim.UUIDv4
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_record_proto_init() }
func file_record_proto_init() {
	if File_record_proto != nil {
		return
	}
	file_uuid_proto_init()
	file_record_proto_msgTypes[2].OneofWrappers = []any{
		(*RunAndRecordResponse_Metadata)(nil),
		(*RunAndRecordResponse_Batch)(nil),
		(*RunAndRecordResponse_Summary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_record_proto_rawDesc), len(file_record_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_record_proto_goTypes,
		DependencyIndexes: file_record_proto_depIdxs,
		EnumInfos:         file_record_proto_enumTypes,
		MessageInfos:      file_record_proto_msgTypes,
	}.Build()
	File_record_proto = out.File
	file_record_proto_goTypes = nil
	file_record_proto_depIdxs = nil
}
