// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: service.proto

package microtraffic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x11micro_traffic_sim\x1a\n" +
	"uuid.proto\x1a\rsession.proto\x1a\n" +
	"cell.proto\x1a\n" +
	"trip.proto\x1a\n" +
	"step.proto\x1a\ttls.proto\x1a\x14conflict_zones.proto2\xb6\x05\n" +
	"\aService\x12T\n" +
	"\n" +
	"NewSession\x12\x1d.micro_traffic_sim.SessionReq\x1a%.micro_traffic_sim.NewSessionResponse\"\x00\x12R\n" +
	"\vInfoSession\x12\x19.micro_traffic_sim.UUIDv4\x1a&.micro_traffic_sim.InfoSessionResponse\"\x00\x12_\n" +
	"\x0fPushSessionGrid\x12\x1e.micro_traffic_sim.SessionGrid\x1a&.micro_traffic_sim.SessionGridResponse\"\x00(\x010\x01\x12_\n" +
	"\x0fPushSessionTrip\x12\x1e.micro_traffic_sim.SessionTrip\x1a&.micro_traffic_sim.SessionTripResponse\"\x00(\x010\x01\x12e\n" +
	"\x15SimulationStepSession\x12\x1e.micro_traffic_sim.SessionStep\x1a&.micro_traffic_sim.SessionStepResponse\"\x00(\x010\x01\x12\\\n" +
	"\x0ePushSessionTLS\x12\x1d.micro_traffic_sim.SessionTLS\x1a%.micro_traffic_sim.SessionTLSResponse\"\x00(\x010\x01\x12z\n" +
	"\x18PushSessionConflictZones\x12'.micro_traffic_sim.SessionConflictZones\x1a/.micro_traffic_sim.SessionConflictZonesResponse\"\x00(\x010\x01B@Z>github.com/LdDl/micro_traffic_sim_grpc/clients/go;microtrafficb\x06proto3"

var file_service_proto_goTypes = []any{
	(*SessionReq)(nil),                   // 0: micro_traffic_sim.SessionReq
	(*UUIDv4)(nil),                       // 1: micro_traffic_sim.UUIDv4
	(*SessionGrid)(nil),                  // 2: micro_traffic_sim.SessionGrid
	(*SessionTrip)(nil),                  // 3: micro_traffic_sim.SessionTrip
	(*SessionStep)(nil),                  // 4: micro_traffic_sim.SessionStep
	(*SessionTLS)(nil),                   // 5: micro_traffic_sim.SessionTLS
	(*SessionConflictZones)(nil),         // 6: micro_traffic_sim.SessionConflictZones
	(*NewSessionResponse)(nil),           // 7: micro_traffic_sim.NewSessionResponse
	(*InfoSessionResponse)(nil),          // 8: micro_traffic_sim.InfoSessionResponse
	(*SessionGridResponse)(nil),          // 9: micro_traffic_sim.SessionGridResponse
	(*SessionTripResponse)(nil),          // 10: micro_traffic_sim.SessionTripResponse
	(*SessionStepResponse)(nil),          // 11: micro_traffic_sim.SessionStepResponse
	(*SessionTLSResponse)(nil),           // 12: micro_traffic_sim.SessionTLSResponse
	(*SessionConflictZonesResponse)(nil), // 13: micro_traffic_sim.SessionConflictZonesResponse
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: micro_traffic_sim.Service.NewSession:input_type -> micro_traffic_sim.SessionReq
	1,  // 1: micro_traffic_sim.Service.InfoSession:input_type -> micro_traffic_sim.UUIDv4
	2,  // 2: micro_traffic_sim.Service.PushSessionGrid:input_type -> micro_traffic_sim.SessionGrid
	3,  // 3: micro_traffic_sim.Service.PushSessionTrip:input_type -> micro_traffic_sim.SessionTrip
	4,  // 4: micro_traffic_sim.Service.SimulationStepSession:input_type -> micro_traffic_sim.SessionStep
	5,  // 5: micro_traffic_sim.Service.PushSessionTLS:input_type -> micro_traffic_sim.SessionTLS
	6,  // 6: micro_traffic_sim.Service.PushSessionConflictZones:input_type -> micro_traffic_sim.SessionConflictZones
	7,  // 7: micro_traffic_sim.Service.NewSession:output_type -> micro_traffic_sim.NewSessionResponse
	8,  // 8: micro_traffic_sim.Service.InfoSession:output_type -> micro_traffic_sim.InfoSessionResponse
	9,  // 9: micro_traffic_sim.Service.PushSessionGrid:output_type -> micro_traffic_sim.SessionGridResponse
	10, // 10: micro_traffic_sim.Service.PushSessionTrip:output_type -> micro_traffic_sim.SessionTripResponse
	11, // 11: micro_traffic_sim.Service.SimulationStepSession:output_type -> micro_traffic_sim.SessionStepResponse
	12, // 12: micro_traffic_sim.Service.PushSessionTLS:output_type -> micro_traffic_sim.SessionTLSResponse
	13, // 13: micro_traffic_sim.Service.PushSessionConflictZones:output_type -> micro_traffic_sim.SessionConflictZonesResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_uuid_proto_init()
	file_session_proto_init()
	file_cell_proto_init()
	file_trip_proto_init()
	file_step_proto_init()
	file_tls_proto_init()
	file_conflict_zones_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
