// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: step.proto

package microtraffic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent type aligned with Rust computation core `AgentType`
// https://docs.rs/micro_traffic_sim_core/0.1.0/micro_traffic_sim_core/agents_types/enum.AgentType.html
type AgentType int32

const (
	// Undefined agent type.
	AgentType_AGENT_TYPE_UNDEFINED AgentType = 0
	// A car agent
	AgentType_AGENT_TYPE_CAR AgentType = 1
	// A bus agent
	AgentType_AGENT_TYPE_BUS AgentType = 2
	// A taxi agent
	AgentType_AGENT_TYPE_TAXI AgentType = 3
	// A pedestrian agent (is not used anywhere currently - **FUTURE WORKS**).
	AgentType_AGENT_TYPE_PEDESTRIAN AgentType = 4
	// A truck agent (e.g., delivery truck, semi-truck).
	AgentType_AGENT_TYPE_TRUCK AgentType = 5
	// A large bus agent (e.g., articulated bus).
	AgentType_AGENT_TYPE_LARGE_BUS AgentType = 6
)

// Enum value maps for AgentType.
var (
	AgentType_name = map[int32]string{
		0: "AGENT_TYPE_UNDEFINED",
		1: "AGENT_TYPE_CAR",
		2: "AGENT_TYPE_BUS",
		3: "AGENT_TYPE_TAXI",
		4: "AGENT_TYPE_PEDESTRIAN",
		5: "AGENT_TYPE_TRUCK",
		6: "AGENT_TYPE_LARGE_BUS",
	}
	AgentType_value = map[string]int32{
		"AGENT_TYPE_UNDEFINED":  0,
		"AGENT_TYPE_CAR":        1,
		"AGENT_TYPE_BUS":        2,
		"AGENT_TYPE_TAXI":       3,
		"AGENT_TYPE_PEDESTRIAN": 4,
		"AGENT_TYPE_TRUCK":      5,
		"AGENT_TYPE_LARGE_BUS":  6,
	}
)

func (x AgentType) Enum() *AgentType {
	p := new(AgentType)
	*p = x
	return p
}

func (x AgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_step_proto_enumTypes[0].Descriptor()
}

func (AgentType) Type() protoreflect.EnumType {
	return &file_step_proto_enumTypes[0]
}

func (x AgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentType.Descriptor instead.
func (AgentType) EnumDescriptor() ([]byte, []int) {
	return file_step_proto_rawDescGZIP(), []int{0}
}

// Run a single simulation step (computation session-bound)
type SessionStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session identifier (UUIDv4)
	SessionId     *UUIDv4 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStep) Reset() {
	*x = SessionStep{}
	mi := &file_step_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStep) ProtoMessage() {}

func (x *SessionStep) ProtoReflect() protoreflect.Message {
	mi := &file_step_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStep.ProtoReflect.Descriptor instead.
func (*SessionStep) Descriptor() ([]byte, []int) {
	return file_step_proto_rawDescGZIP(), []int{0}
}

func (x *SessionStep) GetSessionId() *UUIDv4 {
	if x != nil {
		return x.SessionId
	}
	return nil
}

// Server response for running one simulation step
type SessionStepResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response code (0 = OK)
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Simulation step timestamp (tick)
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Vehicle state data for the current step
	VehicleData []*VehicleState `protobuf:"bytes,4,rep,name=vehicle_data,json=vehicleData,proto3" json:"vehicle_data,omitempty"`
	// Traffic light state data for the current step
	TlsData       []*TLSState `protobuf:"bytes,5,rep,name=tls_data,json=tlsData,proto3" json:"tls_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStepResponse) Reset() {
	*x = SessionStepResponse{}
	mi := &file_step_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStepResponse) ProtoMessage() {}

func (x *SessionStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_step_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStepResponse.ProtoReflect.Descriptor instead.
func (*SessionStepResponse) Descriptor() ([]byte, []int) {
	return file_step_proto_rawDescGZIP(), []int{1}
}

func (x *SessionStepResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SessionStepResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SessionStepResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SessionStepResponse) GetVehicleData() []*VehicleState {
	if x != nil {
		return x.VehicleData
	}
	return nil
}

func (x *SessionStepResponse) GetTlsData() []*TLSState {
	if x != nil {
		return x.TlsData
	}
	return nil
}

// Vehicle state data for single step
type VehicleState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vehicle identifier
	VehicleId int64 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	// Vehicle type
	VehicleType AgentType `protobuf:"varint,2,opt,name=vehicle_type,json=vehicleType,proto3,enum=micro_traffic_sim.AgentType" json:"vehicle_type,omitempty"`
	// Vehicle position (point geometry)
	Point *Point `protobuf:"bytes,3,opt,name=point,proto3" json:"point,omitempty"`
	// Bearing angle (degrees)
	Bearing float64 `protobuf:"fixed64,4,opt,name=bearing,proto3" json:"bearing,omitempty"`
	// Speed. Measured in cells per simulation step.
	Speed int64 `protobuf:"varint,5,opt,name=speed,proto3" json:"speed,omitempty"`
	// Current cell id
	Cell int64 `protobuf:"varint,6,opt,name=cell,proto3" json:"cell,omitempty"`
	// Intermediate cells (cells traversed when speed > 1)
	IntermediateCells []int64 `protobuf:"varint,7,rep,packed,name=intermediate_cells,json=intermediateCells,proto3" json:"intermediate_cells,omitempty"`
	// Travel time (lifetime)
	TravelTime int64 `protobuf:"varint,8,opt,name=travel_time,json=travelTime,proto3" json:"travel_time,omitempty"`
	// Trip identifier
	TripId int64 `protobuf:"varint,9,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	// Tail cells (for multi-cell vehicles)
	TailCells     []int64 `protobuf:"varint,10,rep,packed,name=tail_cells,json=tailCells,proto3" json:"tail_cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleState) Reset() {
	*x = VehicleState{}
	mi := &file_step_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleState) ProtoMessage() {}

func (x *VehicleState) ProtoReflect() protoreflect.Message {
	mi := &file_step_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleState.ProtoReflect.Descriptor instead.
func (*VehicleState) Descriptor() ([]byte, []int) {
	return file_step_proto_rawDescGZIP(), []int{2}
}

func (x *VehicleState) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *VehicleState) GetVehicleType() AgentType {
	if x != nil {
		return x.VehicleType
	}
	return AgentType_AGENT_TYPE_UNDEFINED
}

func (x *VehicleState) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

func (x *VehicleState) GetBearing() float64 {
	if x != nil {
		return x.Bearing
	}
	return 0
}

func (x *VehicleState) GetSpeed() int64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *VehicleState) GetCell() int64 {
	if x != nil {
		return x.Cell
	}
	return 0
}

func (x *VehicleState) GetIntermediateCells() []int64 {
	if x != nil {
		return x.IntermediateCells
	}
	return nil
}

func (x *VehicleState) GetTravelTime() int64 {
	if x != nil {
		return x.TravelTime
	}
	return 0
}

func (x *VehicleState) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

func (x *VehicleState) GetTailCells() []int64 {
	if x != nil {
		return x.TailCells
	}
	return nil
}

// Traffic light state data for single step
type TLSState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Traffic light identifier
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Groups
	Groups        []*TLGroup `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSState) Reset() {
	*x = TLSState{}
	mi := &file_step_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSState) ProtoMessage() {}

func (x *TLSState) ProtoReflect() protoreflect.Message {
	mi := &file_step_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSState.ProtoReflect.Descriptor instead.
func (*TLSState) Descriptor() ([]byte, []int) {
	return file_step_proto_rawDescGZIP(), []int{3}
}

func (x *TLSState) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TLSState) GetGroups() []*TLGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

// Traffic light group state
type TLGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Group identifier
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Signal
	Signal        string `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLGroup) Reset() {
	*x = TLGroup{}
	mi := &file_step_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLGroup) ProtoMessage() {}

func (x *TLGroup) ProtoReflect() protoreflect.Message {
	mi := &file_step_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLGroup.ProtoReflect.Descriptor instead.
func (*TLGroup) Descriptor() ([]byte, []int) {
	return file_step_proto_rawDescGZIP(), []int{4}
}

func (x *TLGroup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TLGroup) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

var File_step_proto protoreflect.FileDescriptor

const file_step_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"step.proto\x12\x11micro_traffic_sim\x1a\n" +
	"uuid.proto\x1a\n" +
	"cell.proto\"G\n" +
	"\vSessionStep\x128\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2\x19.micro_traffic_sim.UUIDv4R\tsessionId\"\xd7\x01\n" +
	"\x13SessionStepResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12B\n" +
	"\fvehicle_data\x18\x04 \x03(\v2\x1f.micro_traffic_sim.VehicleStateR\vvehicleData\x126\n" +
	"\btls_data\x18\x05 \x03(\v2\x1b.micro_traffic_sim.TLSStateR\atlsData\"\xea\x02\n" +
	"\fVehicleState\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\x03R\tvehicleId\x12?\n" +
	"\fvehicle_type\x18\x02 \x01(\x0e2\x1c.micro_traffic_sim.AgentTypeR\vvehicleType\x12.\n" +
	"\x05point\x18\x03 \x01(\v2\x18.micro_traffic_sim.PointR\x05point\x12\x18\n" +
	"\abearing\x18\x04 \x01(\x01R\abearing\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x03R\x05speed\x12\x12\n" +
	"\x04cell\x18\x06 \x01(\x03R\x04cell\x12-\n" +
	"\x12intermediate_cells\x18\a \x03(\x03R\x11intermediateCells\x12\x1f\n" +
	"\vtravel_time\x18\b \x01(\x03R\n" +
	"travelTime\x12\x17\n" +
	"\atrip_id\x18\t \x01(\x03R\x06tripId\x12\x1d\n" +
	"\n" +
	"tail_cells\x18\n" +
	" \x03(\x03R\ttailCells\"N\n" +
	"\bTLSState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x122\n" +
	"\x06groups\x18\x02 \x03(\v2\x1a.micro_traffic_sim.TLGroupR\x06groups\"1\n" +
	"\aTLGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal*\xad\x01\n" +
	"\tAgentType\x12\x18\n" +
	"\x14AGENT_TYPE_UNDEFINED\x10\x00\x12\x12\n" +
	"\x0eAGENT_TYPE_CAR\x10\x01\x12\x12\n" +
	"\x0eAGENT_TYPE_BUS\x10\x02\x12\x13\n" +
	"\x0fAGENT_TYPE_TAXI\x10\x03\x12\x19\n" +
	"\x15AGENT_TYPE_PEDESTRIAN\x10\x04\x12\x14\n" +
	"\x10AGENT_TYPE_TRUCK\x10\x05\x12\x18\n" +
	"\x14AGENT_TYPE_LARGE_BUS\x10\x06B@Z>github.com/LdDl/micro_traffic_sim_grpc/clients/go;microtrafficb\x06proto3"

var (
	file_step_proto_rawDescOnce sync.Once
	file_step_proto_rawDescData []byte
)

func file_step_proto_rawDescGZIP() []byte {
	file_step_proto_rawDescOnce.Do(func() {
		file_step_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_step_proto_rawDesc), len(file_step_proto_rawDesc)))
	})
	return file_step_proto_rawDescData
}

var file_step_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_step_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_step_proto_goTypes = []any{
	(AgentType)(0),              // 0: micro_traffic_sim.AgentType
	(*SessionStep)(nil),         // 1: micro_traffic_sim.SessionStep
	(*SessionStepResponse)(nil), // 2: micro_traffic_sim.SessionStepResponse
	(*VehicleState)(nil),        // 3: micro_traffic_sim.VehicleState
	(*TLSState)(nil),            // 4: micro_traffic_sim.TLSState
	(*TLGroup)(nil),             // 5: micro_traffic_sim.TLGroup
	(*UUIDv4)(nil),              // 6: micro_traffic_sim.UUIDv4
	(*Point)(nil),               // 7: micro_traffic_sim.Point
}
var file_step_proto_depIdxs = []int32{
	6, // 0: micro_traffic_sim.SessionStep.session_id:type_name -> micro_traffic_sim.UUIDv4
	3, // 1: micro_traffic_sim.SessionStepResponse.vehicle_data:type_name -> micro_traffic_sim.VehicleState
	4, // 2: micro_traffic_sim.SessionStepResponse.tls_data:type_name -> micro_traffic_sim.TLSState
	0, // 3: micro_traffic_sim.VehicleState.vehicle_type:type_name -> micro_traffic_sim.AgentType
	7, // 4: micro_traffic_sim.VehicleState.point:type_name -> micro_traffic_sim.Point
	5, // 5: micro_traffic_sim.TLSState.groups:type_name -> micro_traffic_sim.TLGroup
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_step_proto_init() }
func file_step_proto_init() {
	if File_step_proto != nil {
		return
	}
	file_uuid_proto_init()
	file_cell_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_step_proto_rawDesc), len(file_step_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_step_proto_goTypes,
		DependencyIndexes: file_step_proto_depIdxs,
		EnumInfos:         file_step_proto_enumTypes,
		MessageInfos:      file_step_proto_msgTypes,
	}.Build()
	File_step_proto = out.File
	file_step_proto_goTypes = nil
	file_step_proto_depIdxs = nil
}
